language: node_js
branches:
  only:
  - master
before_install:
- npm install -g hexo
- npm install
install:
- hexo generate
deploy:
  provider: s3
  bucket: hexotest.computerlab.io
  region: us-east-1
  access_key_id:
    secure: LX/BidqPXwTLy8p4ELyoN0IkbJSVnsXQGb7kwaeo0ePY+jCrEJ7qs2Jg7ODuaJbMryEM5uyXglreEp/nB1BJDeawPPopEgQVghN76OCdk18LNxMOgxQa75aaPeyRi8n10PgU4q4k/+FDgJO4vsdN6FNTtRo1W0YC+CLrEsh3h05bFXgu/aDaM1Ym8l+mYxzBBtL7BFUwfHsTCyO/g5hxx1W2QCHMRUcsNUO9XH5k9WXa+UKhueULm2jqaLjvUfOB3GGaE0AZbi+7BW6Z2k6lFDeomn1NYDpYVF1+uRTULPg52eD/O5nXIKCW/dVb4aYKcNcaXqG2D8xpFd4euna+Eo1AH8PAB05yiYn1r2WiK7a3NhZAd8yNhFmR/WtMge9564uqXr7FqsV1kvhhyyY7pyPah+9YF2+08yxKhBN179MU4P8PSHiGZ58+RXVpx46EORMxgNCvVDhSCzq4xastDuSf6D+uSAP0CGa7iZUeEiTzV9FlIphJC9T7Oc+RH8Q59MgBRWZsDy/29gSTcD2M4G5FusOHRhAxbwtyBM9YYGKknM3sWnQ8s1BMcpU5N6NgO5qXjhuu+bDo2h0uH+3rdBemZmFoCBKttnfcTf3FMeuzGXmSrQ1yZdvbGWm/UmV6OOe6mxjz2jZs+IYzlZ/px+93eUO+hL3mKqRHarhPATE=
  secret_access_key:
    secure: dBGlpzGt0Dqx+ZqIJRrp0+XuhAQOAgYabwE+kcz8ZC86fnJrfDjYCsBTCmJAQ7fAgdMzAj+V7XtoaQKx7xl6c6ucX713sQcXnePbQICXBmFcNE9A0Q0CRoYyXvDmBJ0BP5viqcg5OahKR5CadxP6lVEtktSoC/5PDf22J6M7Y7swHeRSsiPdb+IM2CLliW/yp3j2VpFluOQkMq3biGHVZrsJElcFbdL+PixdYEsyPmjonytmwLYnQ5PRVBxNg6wOSREBuRUVw9tRzEu1YflIsqLWznQaTwNafHQKZhJk/Xief7DSCQKesknfWn9silTl+cya6iUeLG1fHLivnw2EdtZzGMrozRBvg371d2cAHQsWHTce6fMpjY0GZ5VlRM+XvHi0YUA8FMeVM0nOfN8FA0VwxdgvxoCHukkv97xVNureSAb6oycoBQ6j8UFlnGLcN1IIMZRtow7E1vm5ofpd/ZYENG7fVoM9TSYzXDj3ymAQBlNL7YgnsVNdq/TNxudcMyuOnxeELAocvUhPs1enLTI84MEKfcVz9zfpLriMNW0Fp6IGeOx9R/6WSbde3fUvL0XNT5mokGv9j4zDR4jgR2z//Yzz8YLUS7O+o3yvg4BAdnBgDWq+w2ZzgfYF2G1WYzdpEr57SrIcuGS1DhZwbLfsLnBBFUwaRLWaFH8l8PE=

